server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbcDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        format_sql: true
    show_sql: true